import store from "@/store";

export default [
    {
        path: "pay",
        name: "AdminPay",
        component: () => import("@/views/zhifu/zhifu"),
        meta: { authLogin: true },
    },

    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "yonghu",
        name: "AdminyonghuList",
        component: () => import("@/views/yonghu/list"),
        meta: { title: "用户列表", authLogin: true },
    },
    {
        path: "yonghuadd",
        name: "AdminyonghuAdd",
        component: () => import("@/views/yonghu/add"),
        meta: { title: "添加用户", authLogin: true },
    },
    {
        path: "yonghuupdt",
        name: "AdminyonghuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "yonghuupdtself",
        name: "AdminyonghuUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/yonghu/updt"),
        meta: { title: "编辑用户", authLogin: true },
    },
    {
        path: "liuyanban",
        name: "AdminliuyanbanList",
        component: () => import("@/views/liuyanban/list"),
        meta: { title: "留言板列表", authLogin: true },
    },
    {
        path: "liuyanban_liuyanren",
        name: "AdminliuyanbanListliuyanren",
        component: () => import("@/views/liuyanban/list-liuyanren"),
        meta: { title: "留言板列表", authLogin: true },
    },
    {
        path: "liuyanbanadd",
        name: "AdminliuyanbanAdd",
        component: () => import("@/views/liuyanban/add"),
        meta: { title: "添加留言板", authLogin: true },
    },
    {
        path: "liuyanbanupdt",
        name: "AdminliuyanbanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/liuyanban/updt"),
        meta: { title: "编辑留言板", authLogin: true },
    },
    {
        path: "liuyanbandetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminliuyanbanDetail",
        component: () => import("@/views/liuyanban/detail"),
        meta: { title: "留言板详情", authLogin: true },
    },
    {
        path: "lunbotu",
        name: "AdminlunbotuList",
        component: () => import("@/views/lunbotu/list"),
        meta: { title: "轮播图列表", authLogin: true },
    },
    {
        path: "lunbotuadd",
        name: "AdminlunbotuAdd",
        component: () => import("@/views/lunbotu/add"),
        meta: { title: "添加轮播图", authLogin: true },
    },
    {
        path: "lunbotuupdt",
        name: "AdminlunbotuUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/lunbotu/updt"),
        meta: { title: "编辑轮播图", authLogin: true },
    },
    {
        path: "tushufenlei",
        name: "AdmintushufenleiList",
        component: () => import("@/views/tushufenlei/list"),
        meta: { title: "图书分类列表", authLogin: true },
    },
    {
        path: "tushufenleiadd",
        name: "AdmintushufenleiAdd",
        component: () => import("@/views/tushufenlei/add"),
        meta: { title: "添加图书分类", authLogin: true },
    },
    {
        path: "tushufenleiupdt",
        name: "AdmintushufenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/tushufenlei/updt"),
        meta: { title: "编辑图书分类", authLogin: true },
    },
    {
        path: "tushuxinxi",
        name: "AdmintushuxinxiList",
        component: () => import("@/views/tushuxinxi/list"),
        meta: { title: "图书信息列表", authLogin: true },
    },
    {
        path: "tushuxinxi_faburen",
        name: "AdmintushuxinxiListfaburen",
        component: () => import("@/views/tushuxinxi/list-faburen"),
        meta: { title: "图书信息列表", authLogin: true },
    },
    {
        path: "tushuxinxiadd",
        name: "AdmintushuxinxiAdd",
        component: () => import("@/views/tushuxinxi/add"),
        meta: { title: "添加图书信息", authLogin: true },
    },
    {
        path: "tushuxinxiupdt",
        name: "AdmintushuxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/tushuxinxi/updt"),
        meta: { title: "编辑图书信息", authLogin: true },
    },
    {
        path: "tushuxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmintushuxinxiDetail",
        component: () => import("@/views/tushuxinxi/detail"),
        meta: { title: "图书信息详情", authLogin: true },
    },
    {
        path: "jieyue",
        name: "AdminjieyueList",
        component: () => import("@/views/jieyue/list"),
        meta: { title: "借阅列表", authLogin: true },
    },
    {
        path: "jieyue_faburen",
        name: "AdminjieyueListfaburen",
        component: () => import("@/views/jieyue/list-faburen"),
        meta: { title: "借阅列表", authLogin: true },
    },
    {
        path: "jieyue_jieyueren",
        name: "AdminjieyueListjieyueren",
        component: () => import("@/views/jieyue/list-jieyueren"),
        meta: { title: "借阅列表", authLogin: true },
    },
    {
        path: "jieyueadd",
        name: "AdminjieyueAdd",
        component: () => import("@/views/jieyue/add"),
        meta: { title: "添加借阅", authLogin: true },
    },
    {
        path: "jieyueupdt",
        name: "AdminjieyueUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jieyue/updt"),
        meta: { title: "编辑借阅", authLogin: true },
    },
    {
        path: "jieyuedetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjieyueDetail",
        component: () => import("@/views/jieyue/detail"),
        meta: { title: "借阅详情", authLogin: true },
    },
    {
        path: "guihuan",
        name: "AdminguihuanList",
        component: () => import("@/views/guihuan/list"),
        meta: { title: "归还列表", authLogin: true },
    },
    {
        path: "guihuan_faburen",
        name: "AdminguihuanListfaburen",
        component: () => import("@/views/guihuan/list-faburen"),
        meta: { title: "归还列表", authLogin: true },
    },
    {
        path: "guihuan_jieyueren",
        name: "AdminguihuanListjieyueren",
        component: () => import("@/views/guihuan/list-jieyueren"),
        meta: { title: "归还列表", authLogin: true },
    },
    {
        path: "guihuanadd",
        name: "AdminguihuanAdd",
        component: () => import("@/views/guihuan/add"),
        meta: { title: "添加归还", authLogin: true },
    },
    {
        path: "guihuanupdt",
        name: "AdminguihuanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/guihuan/updt"),
        meta: { title: "编辑归还", authLogin: true },
    },
    {
        path: "guihuandetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminguihuanDetail",
        component: () => import("@/views/guihuan/detail"),
        meta: { title: "归还详情", authLogin: true },
    },
    {
        path: "pinglun",
        name: "AdminpinglunList",
        component: () => import("@/views/pinglun/list"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglun_pinglunren",
        name: "AdminpinglunListpinglunren",
        component: () => import("@/views/pinglun/list-pinglunren"),
        meta: { title: "评论列表", authLogin: true },
    },
    {
        path: "pinglunupdt",
        name: "AdminpinglunUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/pinglun/updt"),
        meta: { title: "编辑评论", authLogin: true },
    },
    {
        path: "jubao",
        name: "AdminjubaoList",
        component: () => import("@/views/jubao/list"),
        meta: { title: "举报列表", authLogin: true },
    },
    {
        path: "jubao_faburen",
        name: "AdminjubaoListfaburen",
        component: () => import("@/views/jubao/list-faburen"),
        meta: { title: "举报列表", authLogin: true },
    },
    {
        path: "jubao_jubaoren",
        name: "AdminjubaoListjubaoren",
        component: () => import("@/views/jubao/list-jubaoren"),
        meta: { title: "举报列表", authLogin: true },
    },
    {
        path: "jubaoadd",
        name: "AdminjubaoAdd",
        component: () => import("@/views/jubao/add"),
        meta: { title: "添加举报", authLogin: true },
    },
    {
        path: "jubaoupdt",
        name: "AdminjubaoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jubao/updt"),
        meta: { title: "编辑举报", authLogin: true },
    },
    {
        path: "jubaodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjubaoDetail",
        component: () => import("@/views/jubao/detail"),
        meta: { title: "举报详情", authLogin: true },
    },
    {
        path: "jubaochuli",
        name: "AdminjubaochuliList",
        component: () => import("@/views/jubaochuli/list"),
        meta: { title: "举报处理列表", authLogin: true },
    },
    {
        path: "jubaochuli_faburen",
        name: "AdminjubaochuliListfaburen",
        component: () => import("@/views/jubaochuli/list-faburen"),
        meta: { title: "举报处理列表", authLogin: true },
    },
    {
        path: "jubaochuli_jubaoren",
        name: "AdminjubaochuliListjubaoren",
        component: () => import("@/views/jubaochuli/list-jubaoren"),
        meta: { title: "举报处理列表", authLogin: true },
    },
    {
        path: "jubaochuli_chuliren",
        name: "AdminjubaochuliListchuliren",
        component: () => import("@/views/jubaochuli/list-chuliren"),
        meta: { title: "举报处理列表", authLogin: true },
    },
    {
        path: "jubaochuliadd",
        name: "AdminjubaochuliAdd",
        component: () => import("@/views/jubaochuli/add"),
        meta: { title: "添加举报处理", authLogin: true },
    },
    {
        path: "jubaochuliupdt",
        name: "AdminjubaochuliUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jubaochuli/updt"),
        meta: { title: "编辑举报处理", authLogin: true },
    },
    {
        path: "jubaochulidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjubaochuliDetail",
        component: () => import("@/views/jubaochuli/detail"),
        meta: { title: "举报处理详情", authLogin: true },
    },
    {
        path: "tushuguanliyuan",
        name: "AdmintushuguanliyuanList",
        component: () => import("@/views/tushuguanliyuan/list"),
        meta: { title: "图书管理员列表", authLogin: true },
    },
    {
        path: "tushuguanliyuanadd",
        name: "AdmintushuguanliyuanAdd",
        component: () => import("@/views/tushuguanliyuan/add"),
        meta: { title: "添加图书管理员", authLogin: true },
    },
    {
        path: "tushuguanliyuanupdt",
        name: "AdmintushuguanliyuanUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/tushuguanliyuan/updt"),
        meta: { title: "编辑图书管理员", authLogin: true },
    },
    {
        path: "tushuguanliyuanupdtself",
        name: "AdmintushuguanliyuanUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/tushuguanliyuan/updt"),
        meta: { title: "编辑图书管理员", authLogin: true },
    },
];
